# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - COMAVISA20250314144249

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'

      - name: Build main project
        run: dotnet build COMAVI_SA.csproj --configuration Release

      - name: Upload main build for publish
        uses: actions/upload-artifact@v4
        with:
          name: main-build
          path: bin/

  test:
    runs-on: windows-latest
    needs: build
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'

      - name: Build and run tests
        shell: pwsh
        run: |
          $testProjectPath = "COMAVIxUnitTest/COMAVIxUnitTest.csproj"
          if (Test-Path $testProjectPath) {
            Write-Host "Test project found at $testProjectPath"
            dotnet build $testProjectPath --configuration Release
            dotnet test $testProjectPath --configuration Release --no-build --verbosity normal
            if ($LASTEXITCODE -ne 0) {
              Write-Host "Tests failed. Pipeline will not proceed to deployment."
              exit 1
            }
          } else {
            Write-Host "WARNING: Test project not found at $testProjectPath. Skipping tests."
          }

  publish:
    runs-on: windows-latest
    needs: test
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'

      - name: dotnet publish
        run: dotnet publish COMAVI_SA.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: publish
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'COMAVISA20250314144249'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_5EDE184A2476400889942253C74CEBFF }}
